### ISSUE TITLE
Retirada excessiva de estrelas no campo "Safe Access" ao utilizar o randomizador

### ISSUE THREAD

**Issue by AbreuEfechou** [SpawW/WFTools#5]
Ao utilizar o preset para 2 ou 3 estrelas, o script está SEMPRE dando um numero ≤ de estrelas para o número escolhido, nunca acima. 
Geralmente quando o local REALMENTE oferece algum risco a segurança, o procedimento recomendado é o de recusar o candidato, então pelo bom senso, se entende que um portal que não está sendo recusado, já é um portal com baixo risco de segurança. Dessa forma, não faz muito sentido a ferramenta sugerir um número menor do que 3 estrelas para um envio, mesmo que seja um candidato mediano.

**Comment by SpawW** [comment]
Tinha um erro de atribuição de valor neste campo realmente. Estava variando entre 1 e 3 estrelas.
Agora irá variar de 2 a 4 estrelas. A atribuição de 5 estrelas será manual neste caso visto que o 3* é justamente para uma situação onde não se tem a certeza de que é um bom portal.
Entendo que até 4* para esta situação pode ajudar, inclusive, na não formação de padrão de voto o que, normalmente, reflete em softban.
